M48
; DRILL file {KiCad (6.0.4)} date Tue Jul 19 15:21:10 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-19T15:21:10-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X0.0Y0.6
X0.0Y0.4
T2
X-0.5Y-0.4
X-0.5Y-0.5
X0.5Y-0.4
X0.5Y-0.5
T0
M30
