backend:
  name: github
  repo: 'envision-projects/envision-projects.github.io'
  base_url: 'https://api.netlify.com'
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: mechanical
    label: 'Mechanical Docs'
    label_singular: 'Mechanical Doc'
    folder: content/mechanical
    create: true
    summary: "{{dirname}}{{filename}} - {{title}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: electrical
    label: 'Electrical Docs'
    label_singular: 'Electrical Doc'
    folder: content/electrical
    create: true
    summary: "{{dirname}}{{filename}} - {{title}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: embedded
    label: 'Embedded Docs'
    label_singular: 'Embedded Doc'
    folder: content/embedded
    create: true
    summary: "{{dirname}}{{filename}} - {{title}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: craft
    label: 'Craft Docs'
    label_singular: 'Craft Doc'
    folder: content/craft
    create: true
    summary: "{{dirname}}{{filename}} - {{title}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: tutorials
    label: 'Tutorials'
    label_singular: 'Tutorial'
    folder: content/tutorials
    create: true
    summary: "{{dirname}}{{filename}} - {{title}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: home
    label: 'Home Files'
    label_singular: 'Home File'
    folder: content
    create: true
    summary: "{{dirname}}{{filename}} - {{title}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }